### ISSUE TITLE
Too many output files

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/data_mgmt_scripts#10]
The current functionality of the script is to output a file for each document. Modify the script to export to one file with each document filename being the first column. If a document has more than one chemical/CAS/etc then it would have multiple lines with the document filename in the first column. If nothing was found in the document then do not include it in the output file.

Definition of Done:

- Only one output file in the output directory

**Comment by scott-8** [comment]
I agree with you, I think the reason I originally did it this way was so that I didn't lose any run progress if an error stopped the script.
