### ISSUE TITLE
download.file saving corrupt .parquet

### ISSUE THREAD

**Issue by WesIngwersen** [HumanExposure/data_mgmt_scripts#14]
https://github.com/HumanExposure/data_mgmt_scripts/blob/b7e0cbcf5326ebbaa4eced5f738d949402ec74d0/prod_chemical_release/scripts/combine_stewi_files_v1.0.5.R#L615

Applicable to all parquet files downloaded in this loop.

When the files are [read in](https://github.com/HumanExposure/data_mgmt_scripts/blob/b7e0cbcf5326ebbaa4eced5f738d949402ec74d0/prod_chemical_release/scripts/combine_stewi_files_v1.0.5.R#L227)
an error is thrown
`Error: IOError: Couldn't deserialize thrift: TProtocolException: Invalid data`

I replicated the same error trying to read in the file using Python pandas read_parquet confirming the corrupt file.

Downloading the same file manually and loading them successfully proved that the files themselves are not corrupt, so the issue must be in the download and writing steps

**Comment by WesIngwersen** [comment]
Using `curl_download()` from the curl library with `mode="wb"` seems to fix this

**Comment by taywll252** [comment]
This issue was addressed and fixed with PR merge.
